- name: set up cart server
  hosts: cart
  become: yes
  tasks:
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enabled nodejs20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install node js
    ansible.builtin.package:
      name: nodejs 
      state: present

  - name: addinng roboshop user
    ansible.builtin.user:
      name: roboshop
      comment: roboshop user
      shell: /sbin/nologin
      home: /app
      system: true
  

   # removing the directory , if we run 2 nd time it will doenload freshly.
  - name: removing the app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creating the app directory
    ansible.builtin.file:
      path: /app
      state: directory

  
  - name: removing the cart application
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent


  - name: downloading the cart application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
      dest: /tmp/cart.zip

  - name: unzip the cart file
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: true


  - name: installing dependencies
    community.general.npm:
      path: /app

  - name: copy cart service file
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: daemon reload and start services
    ansible.builtin.systemd_service:
      state: started
      name: cart 
      enabled: yes
      daemon_reload: true